services:
  postgres:
    image: postgres
    container_name: postgres_crmvendas
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crmvendas
